export const FETCH_HOT_NEWS = "FETCH_HOT_NEWS";
export const TOGGLE_HOT_NEWS = "TOGGLE_HOT_NEWS";
export const DONE_HOT_NEWS = "DONE_HOT_NEWS";

export const FETCH_NEWS_DETAIL = "FETCH_NEWS_DETAIL";
export const TOGGLE_NEWS_DETAIL = "TOGGLE_NEWS_DETAIL";
export const DONE_NEWS_DETAIL = "DONE_NEWS_DETAIL";